# cert-manager

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  creationTimestamp: null
  name: weaveworks-charts
  namespace: flux-system
spec:
  interval: 1m0s
  timeout: 1m0s
  url: https://weaveworks.github.io/weave-gitops-profile-examples/
status: {}

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  labels:
    weave.works/applied-layer: layer-0
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1beta2
        kind: HelmRepository
        name: weaveworks-charts
        namespace: flux-system
      version: 0.0.7
  install:
    crds: CreateReplace
    createNamespace: true
  interval: 1m0s
  targetNamespace: cert-manager
  upgrade:
    crds: CreateReplace
  values:
    cert-manager:
      installCRDs: true
status: {}

---

# policy agent

apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: policy-agent
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/weaveworks/policy-agent
  ref:
    branch: test-terraform
  secretRef:
    name: ssh-credentials

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: policy-agent
  namespace: flux-system
  labels:
    weave.works/applied-layer: layer-1
spec:
  dependsOn:
  - name: cert-manager
    namespace: flux-system
  interval: 1m
  install:
    createNamespace: true
  values:
    config:
      accountId: my-account
      clusterId: my-cluster
      audit:
        enabled: true
        sinks:
          filesystemSink:
            fileName: audit.json
      admission:
        enabled: true
        sinks:
          filesystemSink:
            fileName: admission.json
      terraform:
        enabled: true
        sinks:
          filesystemSink:
            fileName: terraform.json
          k8sEventsSink:
            enabled: true
  chart:
    spec:
      chart: ./helm
      sourceRef:
        kind: GitRepository
        name: policy-agent
        namespace: flux-system
      valuesFiles:
      - ./helm/values.yaml
      interval: 1m
---

# policies

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: policy-library
  namespace: flux-system
  labels:
    weave.works/applied-layer: layer-2
spec:
  interval: 1m0s
  path: ./policies
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

# tf-controller

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 1h0s
  url: https://weaveworks.github.io/tf-controller/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  dependsOn:
  - name: policy-agent
    namespace: flux-system
  chart:
    spec:
      chart: tf-controller
      sourceRef:
        kind: HelmRepository
        name: tf-controller
      version: '>=0.7.0'
  interval: 1h0s
  releaseName: tf-controller
  targetNamespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    replicaCount: 1
    concurrency: 500
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 400m
        memory: 64Mi
    caCertValidityDuration: 10m
    certValidityDuration: 30m
    certRotationCheckFrequency: 1m
    runtimeCreationTimeout: 4m0s
    image:
      tag: main-a20c6bf8
    runner:
      image:
        tag: main-a20c6bf8
    volumes:
    - name: policy-agent-cert
      secret:
        secretName: policy-agent-cert
        optional: false
    volumeMounts:
    - name: policy-agent-cert
      mountPath: /etc/certs/policy-agent.flux-system.svc/
      readOnly: true
