apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: policy-agent-profile
  namespace: default
spec:
  interval: 1m
  url: https://github.com/weaveworks/profiles-catalog
  ref:
    branch: add-policy-set
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: policy-agent-profile
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/weave-policy-agent
      sourceRef:
        kind: GitRepository
        name: policy-agent-profile
        namespace: default
      valuesFiles:
      - ./charts/weave-policy-agent/values.yaml
      interval: 1m
