apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  creationTimestamp: null
  name: weaveworks-charts
  namespace: flux-system
spec:
  interval: 1m0s
  timeout: 1m0s
  url: https://weaveworks.github.io/weave-gitops-profile-examples/
status: {}

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  labels:
    weave.works/applied-layer: layer-0
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1beta2
        kind: HelmRepository
        name: weaveworks-charts
        namespace: flux-system
      version: 0.0.7
  install:
    crds: CreateReplace
    createNamespace: true
  interval: 1m0s
  targetNamespace: cert-manager
  upgrade:
    crds: CreateReplace
  values:
    cert-manager:
      installCRDs: true
status: {}

--- 
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: policy-agent-profile
  namespace: policy-system
spec:
  interval: 1m
  url: https://github.com/weaveworks/profiles-catalog
  ref:
    branch: add-policy-set
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: policy-agent-profile
  namespace: policy-system
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/weave-policy-agent
      sourceRef:
        kind: GitRepository
        name: policy-agent-profile
        namespace: default
      valuesFiles:
      - ./charts/weave-policy-agent/values.yaml
      interval: 1m
