apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: my-service-2
  namespace: default
spec:
  interval: 1m
  url: https://github.com/ahsayde/gitops-apps
  ref:
    branch: main
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-service-2
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./my-service-2/helm
      sourceRef:
        kind: GitRepository
        name: my-service-2
        namespace: default
      valuesFiles:
      - ./my-service-2/helm/values.yaml
      interval: 1m