apiVersion: pac.weave.works/v2beta1
kind: Policy
metadata:
  name: weave.policies.disable-service-account-token-automount-in-specific-namespace
spec:
  id: weave.policies.disable-service-account-token-automount-in-specific-namespace
  name: Disable ServiceAccount Token Automount In Specific Namespace
  enabled: true
  description: "This Policy allows you to enforce the enabling or disabling the automounting of service account tokens. \n\nWhen a pod is created without a service account defined, the default service account within the same namespace will be assigned automatically. \n\nThis is a security concern because a kubernetes client can load a container's service account token. With that token a compromoised contaienr can then access the Kubernetes API to perform actions such as creating and deleting pods.\n\nIn version 1.6+, you can opt out of automounting API credentials for a service account by setting automountServiceAccountToken: false on the service account.\n"
  how_to_solve: "Add the key:value pair `automountServiceAccountToken: false` to your Service Account declaration. \n```\nkind: ServiceAccount\nautomountServiceAccountToken: false\n```\n\nhttps://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server\n"
  category: weave.categories.access-control
  severity: high
  targets:
    kinds:
    - Terraform
  provider: terraform
  code: |
    package magalix.advisor.sa.disable_default_service_account_token_automount
    violation[result] {
      some i
      resource := input.review.object.status.tfplan.planned_values.root_module.resources[i]
      automount_service_account_token := resource.values.automount_service_account_token
      not automount_service_account_token == false
      result = {
        "issue_detected": true,
        "msg": sprintf("automount_service_account_token must be set to 'false'; found '%v'",[automount_service_account_token]),
        "violating_key": sprintf("planned_values.root_module.resources[%d].values.automount_service_account_token", [i]),
        "recommended_value": false
      }
    }
